# Generated by Django 4.2.5 on 2024-05-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilSample',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('point_numb', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('depth', models.CharField(max_length=10)),
                ('depth_index', models.IntegerField()),
                ('sand', models.FloatField()),
                ('silt', models.FloatField()),
                ('clay', models.FloatField()),
                ('sp', models.FloatField()),
                ('ece', models.FloatField()),
                ('ph', models.FloatField()),
                ('oc', models.FloatField()),
                ('n', models.FloatField()),
                ('p', models.FloatField()),
                ('k', models.IntegerField()),
                ('caco3', models.FloatField()),
            ],
        ),
    ]
