# Generated by Django 4.2.5 on 2024-05-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilsample',
            name='CEC',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soilsample',
            name='Gravell',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
